SELECT /*+ PARALLEL(auto) */ EDW.DIM_TIME.YEAR,
  EDW.DIM_TIME.MONTH,
  EDW.DIM_TIME.DAY
...

EXPLAIN PLAN FOR
SELECT ...

SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'ALL'));
