-- UNDER CONSTRUCTION!!!
DEFINE MY_TEXT = 'HELLO, ' || CHR(90) || 'WORLD +' || CHR(90) || ' ASD';
SELECT TRANSLATE(UPPER('&&MY_TEXT'), 'x' || CHR(9) || CHR(10) || CHR(13), 'x') AS DESCRIPTION
FROM DUAL;
