SELECT ALL_TAB_COLUMNS.OWNER,
  ALL_TAB_COLUMNS.TABLE_NAME,
  ALL_TAB_COLUMNS.COLUMN_NAME,
  ALL_TAB_COLUMNS.DATA_TYPE,
  ALL_TAB_COLUMNS.DATA_LENGTH,
  ALL_TAB_COLUMNS.DATA_PRECISION,
  ALL_TAB_COLUMNS.DATA_SCALE,
  ALL_COL_COMMENTS.COMMENTS
FROM ALL_TAB_COLUMNS
LEFT JOIN ALL_COL_COMMENTS
  ON ALL_TAB_COLUMNS.OWNER = ALL_COL_COMMENTS.OWNER
  AND ALL_TAB_COLUMNS.TABLE_NAME = ALL_COL_COMMENTS.TABLE_NAME
  AND ALL_TAB_COLUMNS.COLUMN_NAME = ALL_COL_COMMENTS.COLUMN_NAME
